import type { Component } from "svelte";
import { ConfluenceIntegrationData } from "./confluence/ConfluenceIntegrationData";
import { SharepointIntegrationData } from "./sharepoint/SharepointIntegrationData";
import type { UserIntegration } from "@intric/intric-js";
import type { Writable } from "svelte/store";

export type IntegrationData = {
  /** URL to this integration's logo, usually generated by importing the image via vite */
  logo: string;
  /** Description shown in the admin and account pages */
  description: string;
  /** Name to display for this integration */
  displayName: string;
  /** Label shown in the ImportKnowledgeDialog where the user decides which integration to use */
  importHint: string;
  /** The actual Dialog component that handles the importing for that integrtaion */
  ImportDialog: Component<IntegrationImportDialogProps>;
  /** Label shown for the preview link in the table of IntegrationKnowledge */
  previewLinkLabel: string;
};

export type IntegrationImportDialogProps = {
  goBack: () => void;
  openController: Writable<boolean>;
  integration: UserIntegration;
};

export type IntegrationType = "sharepoint" | "confluence";

export const integrationData: Record<IntegrationType, IntegrationData> = {
  confluence: ConfluenceIntegrationData,
  sharepoint: SharepointIntegrationData
};
