# flake8: noqa

"""add data retention days
Revision ID: 044f3350ffb8
Revises: f8b7664ea8aa
Create Date: 2025-04-15 15:00:57.796452
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = "044f3350ffb8"
down_revision = "f8b7664ea8aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("data_retention_days", sa.Integer(), nullable=True))
    op.add_column("apps", sa.Column("data_retention_days", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "data_retention_days")
    op.drop_column("apps", "data_retention_days")
    # ### end Alembic commands ###
