"""Add unique constraints to integration tables
Revision ID: 43364e1a54f5
Revises: 16ed8ac3ef47
Create Date: 2025-02-12 14:54:12.631284
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = "43364e1a54f5"
down_revision = "16ed8ac3ef47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("ix_integrations_name", table_name="integrations")
    op.create_index(op.f("ix_integrations_name"), "integrations", ["name"], unique=True)
    op.create_unique_constraint(
        "tenant_integration_tenant_id_integration_id_unique",
        "tenant_integrations",
        ["tenant_id", "integration_id"],
    )
    op.drop_column("tenant_integrations", "enabled")
    op.create_unique_constraint(
        "user_integration_user_id_tenant_integration_id_unique",
        "user_integrations",
        ["user_id", "tenant_integration_id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "user_integration_user_id_tenant_integration_id_unique",
        "user_integrations",
        type_="unique",
    )
    op.add_column(
        "tenant_integrations",
        sa.Column(
            "enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        "tenant_integration_tenant_id_integration_id_unique",
        "tenant_integrations",
        type_="unique",
    )
    op.drop_index(op.f("ix_integrations_name"), table_name="integrations")
    op.create_index("ix_integrations_name", "integrations", ["name"], unique=False)

    # ### end Alembic commands ###
