"""Add size column and remove expires_at
Revision ID: 797fdf35cf81
Revises: 88842df42027
Create Date: 2025-03-06 12:47:11.141399
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = "797fdf35cf81"
down_revision = "88842df42027"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("confluence_tokens", "expires_at")
    op.add_column(
        "integration_knowledge", sa.Column("size", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integration_knowledge", "size")
    op.add_column(
        "confluence_tokens",
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
