"""add_state_to_tenants
Revision ID: 88842df42027
Revises: 7c492266359d
Create Date: 2025-03-06 09:47:22.136040
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '88842df42027'
down_revision = '7c492266359d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('state', sa.String(), nullable=True))

    # Set all existing rows to 'active'
    op.execute("UPDATE tenants SET state = 'active' WHERE state IS NULL")

    # Make the column non-nullable now that all rows have a value
    op.alter_column('tenants', 'state', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'state')
    # ### end Alembic commands ###
