# flake8: noqa

"""add type to questions_files
Revision ID: 33ed489d659a
Revises: ff2f32a493f2
Create Date: 2025-03-24 18:13:49.845583
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '33ed489d659a'
down_revision = 'ff2f32a493f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'files',
        'transcription',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.add_column('questions_files', sa.Column('type', sa.String(), nullable=True))
    # Update existing records
    op.execute("UPDATE questions_files SET type = 'user'")
    # Make column not nullable after setting values
    op.alter_column('questions_files', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions_files', 'type')
    op.alter_column(
        'files',
        'transcription',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
