# flake8: noqa

"""remove_tool_assistant_id_from_questions
Revision ID: d6e118655ff5
Revises: abad1a30c0a8
Create Date: 2025-03-12 18:25:05.696794
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic
revision = 'd6e118655ff5'
down_revision = 'abad1a30c0a8'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_tool_assistant_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'tool_assistant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tool_assistant_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_tool_assistant_id_fkey', 'questions', 'assistants', ['tool_assistant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###