"""add group_chat_id to sessions table
Revision ID: 8371fe628586
Revises: b821ca19d819
Create Date: 2025-03-06 09:42:29.011515
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = "8371fe628586"
down_revision = "b821ca19d819"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "group_chats", "allow_mentions", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "group_chats", "show_response_label", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "group_chats", "published", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.add_column("sessions", sa.Column("group_chat_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "sessions", "group_chats", ["group_chat_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sessions_group_chat_id_fkey", "sessions", type_="foreignkey")
    op.drop_column("sessions", "group_chat_id")
    op.alter_column(
        "group_chats", "published", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "group_chats", "show_response_label", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "group_chats", "allow_mentions", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
